In [1]:
import numpy as np #import numpy
import matplotlib.pyplot as plt #for plotting things

1)Using a loop, write code to perform matrix multiplication (in which the answer is composed of elements created by the dot product of the matrices).You should do the multiplication for the two given matrices and check this with numpy's matrix multiplication.

In [2]:
def dotprod(mat_1,mat_2): #define a function, input are two matrices
    if len(mat_1[0])!=len(mat_2): #check if the number of columns and rows match 
        return 'The number of columns in the first matrix needs to be the same as the number of rows in the second column for a successfull matrix multiplication!' #if not, give feedback
    mat_res=np.zeros((len(mat_1),len(mat_2[0]))) #if yes, create a matrix where data will be stored
    for i in range(len(mat_1)): #loop over the number of rows in the first matrix
        for j in range(len(mat_2[0])): #loop over columns in the second metrix
            mat_res[i,j]=sum(mat_1[i]*mat_2[:,j]) #calculates the elements of the result matrix as the sum over the product of the corresponding row in the first matrix and the correspinding column in the second matrix
    return mat_res #returns the result

mat_1,mat_2=np.array([[3,2,-1],[4,0,-3],[7,3,1],[-2,-5,3]]),np.array([[6,7],[3,4],[2,3]]) #input the given matrices
print('The dot product calculated with my self-written function is \n',dotprod(mat_1,mat_2),'.') #answer
print('The dot product calculated with numpy´s matrix multiplication is \n',mat_1.dot(mat_2),'.') #answer
if dotprod(mat_1,mat_2).all()==mat_1.dot(mat_2).all(): #check if each element is the same
    print('They are the same, so my function works!') #answer

The dot product calculated with my self-written function is 
 [[ 22.  26.]
 [ 18.  19.]
 [ 53.  64.]
 [-21. -25.]] .
The dot product calculated with numpy´s matrix multiplication is 
 [[ 22  26]
 [ 18  19]
 [ 53  64]
 [-21 -25]] .
They are the same, so my function works!


2)Write a function which accepts the matrix and vector and solves the system of equations as we discussed in class (creating the upper diagonal matrix). The algorithm for doing this is in the class notes. I would like you to start by writing the pseudocode for the function first, then proceeding on to write this in python. A few tips:
(a) Be sure to define the matrix in such a way that it is not made up of integers (division then may not give you the result you want).
(b) You can use the example done in class to do the testing of your code. 
Once your function is ready, have it solve the given equations. Check your answer using NumPy's "solve" function as we did in class.

Pseudocode:

1.Input the matrix and the vector into the program. Check if it is a square matrix.

2.Get a 1 in the (1,1) position of the matrix (upper left corner) by dividing the whole row of the matrix and the first element of the vecor by the number in (1,1). That procedure will be called "normalization". 

3.Go to the element in (2,1). Subtract a multiple of row 1 from the second row in the matrix and the vector so that the element in (2,1) is zero.

4.Analog to 3. subtract multiples of row 1 from all the remaining rows so that the first column of the matrix is zero everywhere except for the (1,1) element which is 1.

5.Move on to the next diagonal element. Regard all rows above that and smaller columns for future calculations. 

6.Normalize the row so that the diagonal element is 1, analog to step 2.

7.Subtract this row from all rows below, analog to step 3. 

8.Repeat step 5. until 7. until all the matrix is in triangular form and all diagonal elements are 1.

9.Start in the last row, the solution is the last element in the vector.

10.Move one row up, multiply the last element in the row with the just calculated solution (=the last element in the vector) and subtract from the vector element in the second last row. 

11.Move one row up, multiply the last two elements in the row with their corresponding entries in the vector (the already calculated solutions) and subtract from the vector element in the third last row.

12.Repeat analog to step 11. for all rows. 

13.The resulting vector is the solution.

In [3]:
def syssolve(mat,vec): #define function
    if len(mat)!=len(mat[0]): #checks that the matrix is a square matrix
        return 'Error. The matrix has to be a square matrix, the number of rows needs to match the number of columns!' #if not, give feedback
    for i in range(len(mat)): #loop through rows
        checkzero=i #set variable to check if the element is zero and if it is change it
        while checkzero<len(mat) and mat[checkzero,i]==0: #checks if the element is zero and the index is still in range
            checkzero+=1 #moves one row done in search of a nonzero element
        if checkzero==len(mat): #no rows with a nonzero element was found
            return 'The system of equations is either dependent or inconsistent, so there is either no solution or an infinite number of solutions.' #return error text
        if checkzero!=i: #row with nonzero element was found
            mat[[checkzero,i]]=mat[[i,checkzero]] #switch rows before proceeding
            vec[[checkzero,i]]=vec[[i,checkzero]] #switch rows in vector too
        vec[i],mat[i]=vec[i]/mat[i,i],mat[i]/mat[i,i] #"normalises the matrix" - makes the diagonal element 1
        for j in range(i+1,len(mat)): #loops through the rows which still need 0 to make a triangluar matrix
            vec[j],mat[j]=vec[j]-mat[j,i]*vec[i],mat[j]-mat[j,i]*mat[i] #subtracts a multiple of the line above the considered line from the matirx and vector so that the element (j,i) gets 0
    for i in range(len(mat)-1,-1,-1): #loops over the rows, starting from the last towards the first row
        vec[i]-=np.sum(mat[i,i+1:]*vec[i+1:,0]) #calculates each solution element by slicing the matrix and the vector and multiplying the respective elements and then subtracting them from the value in the vector -> result is solution
    return vec #returns the vector

#check with example from class
mat_check=np.array([[2.0,1,4,1],[3,4,-1,-1],[1,-4,1,5],[2,-2,1,3]]) #input matrix
vec_check=np.array([[-4.0],[3],[9],[7]]) #input vector
print('The solution for the system of equations given by the matrix \n',mat_check,'and the vector \n',vec_check) #answer
print('is \n',syssolve(mat_check,vec_check),'.') #answer

The solution for the system of equations given by the matrix 
 [[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]] and the vector 
 [[-4.]
 [ 3.]
 [ 9.]
 [ 7.]]
is 
 [[ 2.]
 [-1.]
 [-2.]
 [ 1.]] .


In [4]:
#calcultaion with given matrix and vector
mat=np.array([[2.0,-1,5,1],[3,2,2,-6],[1,3,3,-1],[5,-2,-3,3]]) #input matrix
vec=np.array([[-3.0],[-32],[-47],[49]]) #input vector
print('The solution calculated with the numpy function is \n',np.linalg.solve(mat,vec),'.') #answer
print('The solution calculated with my own code is \n',syssolve(mat,vec),'.') #answer
if np.linalg.solve(mat,vec).all()==syssolve(mat,vec).all(): #check if each element is the same
    print('They are the same, so my function works!') #answer

The solution calculated with the numpy function is 
 [[  2.]
 [-12.]
 [ -4.]
 [  1.]] .
The solution calculated with my own code is 
 [[  2.]
 [-12.]
 [ -4.]
 [  1.]] .
They are the same, so my function works!


3)The first key to finding eigenvalues of a system is to find the determinant of an equation. Write a function which accepts a matrix, checks to make sure it's square, and if it is, calculates the determinant. For now assume the input has to be of size 3x3 in order to make setting up the multiplication easier. Your method should have the potential to be extendable to higher dimensions, by which I mean that your final sum should loop over the dimension of the matrix and not just be an  addition  of  all of the elements individually. You should find the determinant of the given matrix and check with the numpy function.

In [5]:
def det(mat): #define function, input is a matirx
    if len(mat)!=len(mat[0]): #checks that the matrix is a square matrix
        return 'Error. The matrix has to be a square matrix, the number of rows needs to match the number of columns!' #if not, give feedback
    det=1 #set determinant starting value, 1 instead of 0 because multiplication is used 
    for i in range(len(mat)): #loop through rows
        checkzero=i #set variable to check if the element is zero and if it is change it
        while checkzero<len(mat) and mat[checkzero,i]==0: #checks if the element is zero and the index is still in range
            checkzero+=1 #moves one row done in search of a nonzero element
        if checkzero==len(mat): #no rows with a nonzero element was found
            return 0 #determinant is zero
        if checkzero!=i: #row with nonzero element was found
            mat[[checkzero,i]]=mat[[i,checkzero]] #switch rows before proceeding
            mat[i]*=-1 #switching rows changes the sign of the determinant, needs to be corrected
        for j in range(i+1,len(mat)): #loops through the rows which still need 0 to make a triangluar matrix
            mat[j]=mat[j]-mat[j,i]/mat[i,i]*mat[i] #calculates the ratio of the first nonzero element of the row with the element below it and uses that ratio so do a addition so that the element n the lower row gets 0
        det*=mat[i,i] #multiplies the newly won diagonal element to the matrix
    return det #returns the determinant

mat=np.array([[2.0,-1,5],[3,2,2],[1,3,-1]]) #input matrix
print('The determinant determined with my self-written code is',det(mat),'.') #answer
print('The determinant determined with the numpy function is',round(np.linalg.det(mat),6),'.') #answer
if det(mat)==round(np.linalg.det(mat),3): #check if each element is the same
    print('They are the same, so my function works!') #answer

The determinant determined with my self-written code is 14.0 .
The determinant determined with the numpy function is 14.0 .
They are the same, so my function works!
